FROM python:3.8-alpine
ENV NAME=nachoenv
ENV PORT=7777
WORKDIR /app 
COPY ./requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt
COPY ./src/gunicorn_config.py .
COPY ./src/server.py .
EXPOSE ${PORT}
CMD ["gunicorn","-c","/app/gunicorn_config.py","server:app"]
